### PR TITLE
Refactor the entire admin so it's better and has a tab in editor

### LINKED ISSUE #43: Caldera Forms Pro tab in form editor
- [ ] Settings for layouts
- [ ] Settings for pdf
- [ ] Nptice re: keys
- [ ] Notice re: no layouts
- [ ] Notice re: entry tracking not on
- [ ] UTMs for links in email

### PR DESCRIPTION
**Pull request by Shelob9**
Fixes #43 and #53 

Total rewrite from scratch of admin. Uses webpack and vuex to make everything about vue -- OK there is some dumb shit with the index.html, and I don't totally grok how to use vuex without being overly verbose, which they provide ways to avoid -- be JavaScript Of Industry.

Also, the main settings page is now way more compact, no more than 4 settings on the screen at a time. Needs some CSS, but -
screenshot from 2017-09-24 22-38-54
screenshot from 2017-09-24 22-46-10
screenshot from 2017-09-24 22-45-47

Pretty good I think.

And there is a tab, which is a separate view from the settings page, but is composed of the same components:

screenshot from 2017-09-24 22-49-36

BTW The settings for the form are loaded and saved via the REST API. Save doesn't follow form save, happens automatically. There is no save button, I'm beginning to think their should never been a save button.

### CODE REVIEW

**Comment by andykillen** [comment]
maybe there should not be a save button, but there should be some sort of on-screen recognition that saving has been performed.  (in my opinion)

**Comment by Shelob9** [comment]
@andykillen That's fair, also, I need to wire the old alert status component to vuex.

**Comment by Shelob9** [comment]
TODO
- [ ] Translations
- [x] Status component
- [ ] Not connected to CF Pro message in tab
- [x] No layouts alert in tab

**Comment by andykillen** [comment]
I might be able to get Chinese, Arabic and Dutch translations ready for you.  Let me know when the UI is stable and all needed words are in place.

**Review by Shelob9 — COMMENTED** [review]
#61

**Comment by Shelob9** [comment]
OK. This is done. Great job. Real happy with results and what we learned along the way. Points awarded to @New0  I'm cool with merging this except: 

1) The unboarding docs will be out of date. I will fix, not that big of a deal.
2) Even though we didn't touch the functionality of plugin, and this fix maintains, dare I say reinforces the decoupling between UI and functionality, but still, we should make sure this plugin still sends emails and stuff.
3) I want to avoid using an HTML file for Webpack like I am, but if I don't fix that right now, whatever.

**Comment by Shelob9** [comment]
Docs are done. I've tested it. I was going to merge, but then I realized it was Friday night at 9:15PM LOL. Do it on monday.

**Comment by Shelob9** [comment]
@New0  IT HAPPENED!

**Pull request merged**
